#!/usr/bin/env php
<?php

set_time_limit(0);

$core = require_once __DIR__.'/bootstrap.php';

$application = $core['console'];

/** @todo - write own provider... */

/** Example */
// $application->add( new MyCommand() );
$application->run();

?>